/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.Stock;
import service.StockService;

/**
 *
 * @author qanh2
 */
public class AddStockFrame extends javax.swing.JFrame {

    StockService stockService;
    Stock stock;

    public AddStockFrame() {
        initComponents();
        stockService = new StockService();
        stock = new Stock();
        autoStockID();
        this.setLocationRelativeTo(null);
    }

    private void autoStockID() {
        int autoID;
        try {
            String sql;
            Connection cn;
            cn = dao.JDBCConection.getConnection();
            PreparedStatement pstm;
            ResultSet rs;
            sql = "Select max(item_code) from Stock";
            pstm = cn.prepareStatement(sql);
            rs = pstm.executeQuery();

            if (rs.next()) {
                autoID = rs.getInt(1);
                autoID++;
                txtId.setText(Integer.toString(autoID));
            } else {
                txtId.setText("1");
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    }

    private boolean validateform() {
        String textPattern = "^[a-zA-Z0-9]+( [a-zA-Z0-9]+)*$";
        String numberPattern = "^[0-9]{1,20}$";
        String str;
        Pattern ptn;
        Matcher mc;
        try {
            //Iteam Name
            str = txtIname.getText();
            if (str.isEmpty()) {
                txtIname.grabFocus();
                throw new Exception("Iteam Name cannot be blank");
            }
            ptn = Pattern.compile(textPattern);
            mc = ptn.matcher(str);
            if (!mc.matches()) {
                txtIname.grabFocus();
                throw new Exception("Iteam Name contain more blank");
            }
            //Iteam Cost
            str = txtIcost.getText();
            if (str.isEmpty()) {
                txtIcost.grabFocus();
                throw new Exception("Iteam Cost cannot be blank");
            }
            ptn = Pattern.compile(numberPattern);
            mc = ptn.matcher(str);
            if (!mc.matches()) {
                txtIcost.grabFocus();
                throw new Exception("Iteam Cost must a number");
            }
            //Item Available
            str = txtInum.getText();
            if (str.isEmpty()) {
                txtInum.grabFocus();
                throw new Exception("Iteam Cost cannot be blank");
            }
            ptn = Pattern.compile(numberPattern);
            mc = ptn.matcher(str);
            if (!mc.matches()) {
                txtInum.grabFocus();
                throw new Exception("Iteam Cost must a number");
            }
            //Items Consumed
            str = txtDnum.getText();
            if (str.isEmpty()) {
                txtDnum.grabFocus();
                throw new Exception("Iteam Cost cannot be blank");
            }
            ptn = Pattern.compile(numberPattern);
            mc = ptn.matcher(str);
            if (!mc.matches()) {
                txtDnum.grabFocus();
                throw new Exception("Iteam Cost must a number");
            }
            
            return true;

        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a number");
            return false;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtIname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        sbBtn = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIcost = new javax.swing.JTextField();
        txtInum = new javax.swing.JTextField();
        txtDnum = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setText("Item Name");

        jLabel4.setText("Item Cost");

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        sbBtn.setText("Submit");
        sbBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbBtnActionPerformed(evt);
            }
        });

        txtId.setEditable(false);

        jLabel3.setText("ID");

        jLabel6.setText("Item Available");

        jLabel7.setText("Items Consumed");

        txtIcost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIcostActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(102, 176, 50));

        jLabel1.setBackground(new java.awt.Color(102, 176, 50));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADD STOCK");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sbBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 50, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(10, 10, 10))
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtIname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                            .addComponent(txtIcost, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtInum, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDnum, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtId))
                        .addGap(69, 69, 69))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIname, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtIcost, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtInum, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDnum, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sbBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        new ListStockJPanel().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void sbBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbBtnActionPerformed
        if (validateform() == true) {
            stock.setId(Integer.parseInt(txtId.getText()));
            stock.setIname(txtIname.getText());
            stock.setIcost(Integer.parseInt(txtIcost.getText()));
            stock.setInum(Integer.parseInt(txtInum.getText()));
            stock.setDnum(Integer.parseInt(txtDnum.getText()));

            stockService.addStock(stock);

            new ListStockJPanel().setVisible(true);
            this.dispose();
        }else {
            JOptionPane.showMessageDialog(null, "Add Fail!");
        }
    }//GEN-LAST:event_sbBtnActionPerformed

    private void txtIcostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIcostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIcostActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton sbBtn;
    private javax.swing.JTextField txtDnum;
    private javax.swing.JTextField txtIcost;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIname;
    private javax.swing.JTextField txtInum;
    // End of variables declaration//GEN-END:variables
}
