/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.User;
import service.UserService;

/**
 *
 * @author qanh2
 */
public class AddUserFrame extends javax.swing.JFrame {

    UserService userService;
    User user;

    public AddUserFrame() {
        initComponents();
        userService = new UserService();
        user = new User();
//        String type = "adm";
//        if (adRadioButton.isSelected()) {
//            type = "adm";
//            autoIDAd();
//
//        }
//        if (docRadioButton.isSelected()) {
//            type = "doc";
//            autoIDDo();
//
//        }
//        if (staRadioButton.isSelected()) {
//            type = "sta";
//            autoIDSt();
//
//        }
    }

    private void autoIDAd() {
        try {
            String sql;
            Connection cn;
            cn = dao.JDBCConection.getConnection();
            PreparedStatement pstm;
            ResultSet rs;
            sql = "Select top 1 id from Account order by id desc";
            pstm = cn.prepareStatement(sql);
            rs = pstm.executeQuery();
            rs.next();
            String test = rs.getString("id");
            String subtest = test.substring(3, 6);
            Integer subnum = Integer.parseInt(subtest) + 1;
            
            if (subnum > 0 && subnum < 10) {
                txtId.setText("adm00" + subnum);
            } else if (subnum < 100) {
                txtId.setText("adm0" + subnum);
            } else {
                txtId.setText("adm" + subnum);
            }

        } catch (Exception e) {
            e.getStackTrace();
        }
    }

    private void autoIDDo() {
        try {
            String sql;
            Connection cn;
            cn = dao.JDBCConection.getConnection();
            PreparedStatement pstm;
            ResultSet rs;
            sql = "Select top 1 id from Account order by id desc";
            pstm = cn.prepareStatement(sql);
            rs = pstm.executeQuery();
            rs.next();
            String test = rs.getString("id");
            String subtest = test.substring(3, 6);
            Integer subnum = Integer.parseInt(subtest) + 1;
            
            if (subnum > 0 && subnum < 10) {
                txtId.setText("doc00" + subnum);
            } else if (subnum < 100) {
                txtId.setText("doc0" + subnum);
            } else {
                txtId.setText("doc" + subnum);
            }
        } catch (Exception e) {
            e.getStackTrace();
        }
    }

    private void autoIDSt() {
        try {
            String sql;
            Connection cn;
            cn = dao.JDBCConection.getConnection();
            PreparedStatement pstm;
            ResultSet rs;
            sql = "Select top 1 id from Account order by id desc";
            pstm = cn.prepareStatement(sql);
            rs = pstm.executeQuery();
            rs.next();
            String test = rs.getString("id");
            String subtest = test.substring(3, 6);
            Integer subnum = Integer.parseInt(subtest) + 1;
        
            if (subnum > 0 && subnum < 10) {
                txtId.setText("sta00" + subnum);
            } else if (subnum < 100) {
                txtId.setText("sta0" + subnum);
            } else {
                txtId.setText("sta" + subnum);
            }
        } catch (Exception e) {
            e.getStackTrace();
        }
    }

    private boolean validateform() {
        String textPattern = "^[a-zA-Z0-9]+( [a-zA-Z0-9]+)*$";

        String str;
        Pattern ptn;
        Matcher mc;
        try {
            //login name
            str = txtUser.getText();
            if (str.isEmpty()) {
                txtUser.grabFocus();
                throw new Exception("Login cannot be blank");
            }
            ptn = Pattern.compile(textPattern);
            mc = ptn.matcher(str);
            if (!mc.matches()) {
                txtUser.grabFocus();
                throw new Exception("Login Name contain more blank");
            }
            //pass
            str = txtPass.getText();
            if (str.length() < 4 || str.length() > 12) {
                txtPass.grabFocus();
                throw new Exception("Password must be greater than 4 and lesser than 12.");
            }
            return true;

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        adRadioButton = new javax.swing.JRadioButton();
        staRadioButton = new javax.swing.JRadioButton();
        docRadioButton = new javax.swing.JRadioButton();
        backBtn = new javax.swing.JButton();
        sbBtn = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("User Name ");

        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });

        jLabel4.setText("Password");

        jLabel5.setText("Type");

        buttonGroup1.add(adRadioButton);
        adRadioButton.setSelected(true);
        adRadioButton.setText("Admin");

        buttonGroup1.add(staRadioButton);
        staRadioButton.setText("Staff");

        buttonGroup1.add(docRadioButton);
        docRadioButton.setText("Doctor");

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        sbBtn.setText("Submit");
        sbBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbBtnActionPerformed(evt);
            }
        });

        txtId.setEditable(false);

        jLabel3.setText("ID");

        jPanel1.setBackground(new java.awt.Color(102, 176, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add User");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUser)
                            .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                            .addComponent(txtId)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(adRadioButton)
                                .addGap(34, 34, 34)
                                .addComponent(docRadioButton)
                                .addGap(50, 50, 50)
                                .addComponent(staRadioButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(sbBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backBtn)
                        .addGap(68, 68, 68)))
                .addContainerGap(61, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(adRadioButton)
                    .addComponent(docRadioButton)
                    .addComponent(staRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(sbBtn))
                .addGap(82, 82, 82))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        new ListUserJPanel().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void sbBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbBtnActionPerformed
        if (validateform() == true) {
            user.setUser(txtUser.getText());
            user.setPass(String.valueOf(txtPass.getPassword()));
            String type = "adm";
            if (adRadioButton.isSelected()) {
                type = "adm";
                autoIDAd();

            }
            if (docRadioButton.isSelected()) {
                type = "doc";
                autoIDDo();

            }
            if (staRadioButton.isSelected()) {
                type = "sta";
                autoIDSt();

            }
            user.setType(type);

            user.setId(txtId.getText());
            userService.addUser(user);
            JOptionPane.showMessageDialog(this, "Add Success");
            new ListUserJPanel().setVisible(true);
            this.dispose();

    }//GEN-LAST:event_sbBtnActionPerformed
    }
    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton adRadioButton;
    private javax.swing.JButton backBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton docRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton sbBtn;
    private javax.swing.JRadioButton staRadioButton;
    private javax.swing.JTextField txtId;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
